fix: get bootstrap lock

diff --git a/bootstrap/cloud-config.yaml b/bootstrap/cloud-config.yaml
--- a/bootstrap/cloud-config.yaml
+++ b/bootstrap/cloud-config.yaml
@@ -101,6 +101,10 @@ stages:
                       content: |
                         #!/bin/bash
                         set -x -e
+                        if ! /tmp/get-manifest-lock.sh bootstrap-lock; then
+                          echo "Lock was not obtained"
+                          exit 0
+                        fi
                         # General
                         kubectl apply --server-side --kustomize github.com/6ixfalls/homelab-gitops.git//bootstrap/manifests
                         # Flux
@@ -133,6 +137,51 @@ stages:
         KUBECONFIG: /etc/rancher/k3s/k3s.yaml
         CONTAINERD_ADDRESS: /run/k3s/containerd/containerd.sock
         CONTAINERD_NAMESPACE: k8s.io
+    - name: "Drop initialization lock script"
+      files:
+        - path: /tmp/get-manifest-lock.sh
+          content: |
+            #!/bin/bash
+            # Try for 30 minutes, with 15 second intervals
+            minutes=30
+            sleep=15
+            retry_attempt=1
+            total_attempts=$(( minutes * 60 / sleep ))
+            active="false"
+
+            while [[ $retry_attempt -le $total_attempts ]]; do
+              if [[ "$active" != "true" ]]; then
+                # Ensure only one host tries to bootstrap, whichever makes the configmap first
+                if ! timeout 5 kubectl version &> /dev/null; then
+                  echo "Kubernetes API not ready yet, sleeping"
+                else
+                  if ! timeout 5 kubectl create configmap $1 --from-literal=hostname="$(hostname)"; then
+                    echo "Unable to create configmap, another node may be active"
+                  fi
+
+                  # The configmap exists but we must finally check if the hostname matches
+                  if [[ "$(timeout 5 kubectl get configmap -n default $1 -o jsonpath='{.data.hostname}')" != "$(hostname)" ]]; then
+                    echo "Bootstrap ConfigMap exists but another node is active, exiting..."
+                    exit 3
+                  fi
+
+                  # We must be the active node
+                  active="true"
+                fi
+              fi
+                
+              if [[ "$active" == "true" ]]; then
+                exit 0
+              fi
+
+              echo "Install attempt $retry_attempt (of $total_attempts) failed, retrying in $sleep seconds"
+              (( retry_attempt = retry_attempt + 1 ))
+              sleep $sleep
+            done
+
+            # Failed all attempts
+            exit 2
+          permissions: 0777
   "kairos-install.after":
     - name: "Enable k3s ready units"
       commands:
