feat: fix cluster bootstrapping

diff --git a/bootstrap/cloud-config.yaml b/bootstrap/cloud-config.yaml
--- a/bootstrap/cloud-config.yaml
+++ b/bootstrap/cloud-config.yaml
@@ -64,7 +64,138 @@ stages:
               args:
                 - --server https://10.17.4.111:6443
             {{- end }}
+            {{- if $first }}
+            stages:
+              'kairos-agent.bootstrap':
+                - name: "Drop external secret"
+                  if: "[ ! -e /var/lib/rancher/k3s/server/manifests/cluster-secrets.yaml ] && [ -e /etc/rancher/k3s/k3s.yaml ]"
+                  files:
+                    - path: /var/lib/rancher/k3s/server/manifests/cluster-secrets.yaml
+                      content: |
+                        apiVersion: v1
+                        data:
+                          environment: cHJk
+                          dopplerToken: {{ DOPPLER_TOKEN }}
+                          dopplerProject: {{ DOPPLER_PROJECT }}
+                          clusterDomain: {{ CLUSTER_DOMAIN }}
+                        kind: Secret
+                        metadata:
+                          name: cluster-secrets
+                          namespace: flux-system
+                - name: "Add cluster-specific manifests: Flux"
+                  if: "[ ! -e /var/lib/rancher/k3s/server/manifests/flux.applied ] && [ -e /etc/rancher/k3s/k3s.yaml ]"
+                  files:
+                    - path: /tmp/flux-manifest.sh
+                      content: |
+                        #!/bin/bash
+                        set -x
+                        kubectl apply --server-side --kustomize github.com/6ixfalls/homelab-gitops.git//bootstrap
+                        kubectl apply --server-side --kustomize github.com/6ixfalls/homelab-gitops.git//clusters/hutao/flux/config
+                        touch /var/lib/rancher/k3s/server/manifests/flux.applied
+                      permissions: 0777
+                  commands:
+                    - "KUBECONFIG=/etc/rancher/k3s/k3s.yaml nohup /bin/bash /tmp/flux-manifest.sh > /tmp/flux-apply.out 2>&1 &"
+                - name: "Add cluster-specific manifests: Cilium"
+                  if: "[ ! -e /var/lib/rancher/k3s/server/manifests/cilium-helmchart.applied ] && [ -e /etc/rancher/k3s/k3s.yaml ]"
+                  downloads:
+                    - url: https://raw.githubusercontent.com/6ixfalls/homelab-gitops/main/bootstrap/cilium.yaml
+                      path: /var/lib/rancher/k3s/server/manifests/cilium-helmchart.yaml
+                  files:
+                    - path: /tmp/cilium-manifest.sh
+                      content: |
+                        #!/bin/bash
+                        NAMESPACE="kube-system"
+                        HELM_CHART_NAME="cilium"
+                        KUBECONFIG="/etc/rancher/k3s/k3s.yaml"
 
+                        if ! /tmp/get-manifest-lock.sh $HELM_CHART_NAME; then
+                          echo "Lock was not obtained"
+                          exit 0
+                        fi
+
+                        helm_release_exists() {
+                          kubectl get helmchart ${HELM_CHART_NAME} -n ${NAMESPACE} &> /dev/null
+                        }
+
+                        while ! helm_release_exists; do
+                          echo "Helm release not found. Retrying in 5 seconds..."
+                          sleep 5
+                        done
+
+                        # Wait for HelmChart to rollout
+                        if kubectl wait --for=condition=complete job/helm-install-${HELM_CHART_NAME} -n ${NAMESPACE} --timeout=20m; then
+                          # Patch the HelmChart to unmanage it
+                          kubectl patch helmchart ${HELM_CHART_NAME} -n ${NAMESPACE} \
+                              --type=json -p='[{"op": "add", "path": "/metadata/annotations/helmcharts.helm.cattle.io~1unmanaged", "value": "true"}]'
+
+                          # Delete the HelmChart CR
+                          kubectl delete helmchart ${HELM_CHART_NAME} -n ${NAMESPACE} &
+
+                          # Force delete the HelmChart
+                          kubectl patch helmchart ${HELM_CHART_NAME} -n ${NAMESPACE} \
+                              --type=json -p='[{"op": "replace", "path": "/metadata/finalizers", "value": []}]'
+
+                          # Delete the manifests
+                          rm -f /var/lib/rancher/k3s/server/manifests/cilium-helmchart.yaml
+                          touch /var/lib/rancher/k3s/server/manifests/cilium-helmchart.applied
+                        else
+                          echo "${HELM_CHART_NAME} HelmChart rollout did not complete successfully within 20 minutes."
+                          exit 1
+                        fi
+                      permissions: 0777
+                  commands:
+                    - "KUBECONFIG=/etc/rancher/k3s/k3s.yaml nohup /bin/bash /tmp/cilium-manifest.sh > /tmp/cilium-apply.out 2>&1 &"
+                - name: "Add cluster-specific manifests: kube-vip"
+                  if: "[ ! -e /var/lib/rancher/k3s/server/manifests/kube-vip-helmchart.applied ] && [ -e /etc/rancher/k3s/k3s.yaml ]"
+                  downloads:
+                    - url: https://raw.githubusercontent.com/6ixfalls/homelab-gitops/main/bootstrap/kube-vip.yaml
+                      path: /var/lib/rancher/k3s/server/manifests/kube-vip-helmchart.yaml
+                  files:
+                    - path: /tmp/kube-vip-manifest.sh
+                      content: |
+                        #!/bin/bash
+                        NAMESPACE="kube-system"
+                        HELM_CHART_NAME="kube-vip"
+                        KUBECONFIG="/etc/rancher/k3s/k3s.yaml"
+
+                        if ! /tmp/get-manifest-lock.sh $HELM_CHART_NAME; then
+                          echo "Lock was not obtained"
+                          exit 0
+                        fi
+
+                        helm_release_exists() {
+                          kubectl get helmchart ${HELM_CHART_NAME} -n ${NAMESPACE} &> /dev/null
+                        }
+
+                        while ! helm_release_exists; do
+                          echo "Helm release not found. Retrying in 5 seconds..."
+                          sleep 5
+                        done
+
+                        # Wait for HelmChart to rollout
+                        if kubectl wait --for=condition=complete job/helm-install-${HELM_CHART_NAME} -n ${NAMESPACE} --timeout=20m; then
+                          # Patch the HelmChart to unmanage it
+                          kubectl patch helmchart ${HELM_CHART_NAME} -n ${NAMESPACE} \
+                              --type=json -p='[{"op": "add", "path": "/metadata/annotations/helmcharts.helm.cattle.io~1unmanaged", "value": "true"}]'
+
+                          # Delete the HelmChart CR
+                          kubectl delete helmchart ${HELM_CHART_NAME} -n ${NAMESPACE} &
+
+                          # Force delete the HelmChart
+                          kubectl patch helmchart ${HELM_CHART_NAME} -n ${NAMESPACE} \
+                              --type=json -p='[{"op": "replace", "path": "/metadata/finalizers", "value": []}]'
+
+                          # Delete the manifests
+                          rm -f /var/lib/rancher/k3s/server/manifests/kube-vip-helmchart.yaml
+                          touch /var/lib/rancher/k3s/server/manifests/kube-vip-helmchart.applied
+                        else
+                          echo "${HELM_CHART_NAME} HelmChart rollout did not complete successfully within 20 minutes."
+                          exit 1
+                        fi
+                      permissions: 0777
+                  commands:
+                    - "KUBECONFIG=/etc/rancher/k3s/k3s.yaml nohup /bin/bash /tmp/kube-vip-manifest.sh > /tmp/kube-vip-apply.out 2>&1 &"
+            {{- end }}
   boot:
     - name: "Set up various kube environment variables"
       environment:
@@ -116,132 +247,3 @@ stages:
             # Failed all attempts
             exit 2
           permissions: 0777
-  "provider-kairos.bootstrap.after.master":
-    - name: "Drop external secret"
-      if: "[ ! -e /var/lib/rancher/k3s/server/manifests/cluster-secrets.yaml ] && [ -e /etc/rancher/k3s/k3s.yaml ]"
-      files:
-        - path: /var/lib/rancher/k3s/server/manifests/cluster-secrets.yaml
-          content: |
-            apiVersion: v1
-            data:
-              environment: cHJk
-              dopplerToken: {{ DOPPLER_TOKEN }}
-              dopplerProject: {{ DOPPLER_PROJECT }}
-              clusterDomain: {{ CLUSTER_DOMAIN }}
-            kind: Secret
-            metadata:
-              name: cluster-secrets
-              namespace: flux-system
-    - name: "Add cluster-specific manifests: Flux"
-      if: "[ ! -e /var/lib/rancher/k3s/server/manifests/flux.applied ] && [ -e /etc/rancher/k3s/k3s.yaml ]"
-      files:
-        - path: /tmp/flux-manifest.sh
-          content: |
-            #!/bin/bash
-            set -x
-            kubectl apply --server-side --kustomize github.com/6ixfalls/homelab-gitops.git//bootstrap
-            kubectl apply --server-side --kustomize github.com/6ixfalls/homelab-gitops.git//clusters/hutao/flux/config
-            touch /var/lib/rancher/k3s/server/manifests/flux.applied
-          permissions: 0777
-      commands:
-        - "KUBECONFIG=/etc/rancher/k3s/k3s.yaml nohup /bin/bash /tmp/flux-manifest.sh > /tmp/flux-apply.out 2>&1 &"
-    - name: "Add cluster-specific manifests: Cilium"
-      if: "[ ! -e /var/lib/rancher/k3s/server/manifests/cilium-helmchart.applied ] && [ -e /etc/rancher/k3s/k3s.yaml ]"
-      downloads:
-        - url: https://raw.githubusercontent.com/6ixfalls/homelab-gitops/main/bootstrap/cilium.yaml
-          path: /var/lib/rancher/k3s/server/manifests/cilium-helmchart.yaml
-      files:
-        - path: /tmp/cilium-manifest.sh
-          content: |
-            #!/bin/bash
-            NAMESPACE="kube-system"
-            HELM_CHART_NAME="cilium"
-            KUBECONFIG="/etc/rancher/k3s/k3s.yaml"
-
-            if ! /tmp/get-manifest-lock.sh $HELM_CHART_NAME; then
-              echo "Lock was not obtained"
-              exit 0
-            fi
-
-            helm_release_exists() {
-              kubectl get helmchart ${HELM_CHART_NAME} -n ${NAMESPACE} &> /dev/null
-            }
-
-            while ! helm_release_exists; do
-              echo "Helm release not found. Retrying in 5 seconds..."
-              sleep 5
-            done
-
-            # Wait for HelmChart to rollout
-            if kubectl wait --for=condition=complete job/helm-install-${HELM_CHART_NAME} -n ${NAMESPACE} --timeout=20m; then
-              # Patch the HelmChart to unmanage it
-              kubectl patch helmchart ${HELM_CHART_NAME} -n ${NAMESPACE} \
-                  --type=json -p='[{"op": "add", "path": "/metadata/annotations/helmcharts.helm.cattle.io~1unmanaged", "value": "true"}]'
-
-              # Delete the HelmChart CR
-              kubectl delete helmchart ${HELM_CHART_NAME} -n ${NAMESPACE} &
-
-              # Force delete the HelmChart
-              kubectl patch helmchart ${HELM_CHART_NAME} -n ${NAMESPACE} \
-                  --type=json -p='[{"op": "replace", "path": "/metadata/finalizers", "value": []}]'
-
-              # Delete the manifests
-              rm -f /var/lib/rancher/k3s/server/manifests/cilium-helmchart.yaml
-              touch /var/lib/rancher/k3s/server/manifests/cilium-helmchart.applied
-            else
-              echo "${HELM_CHART_NAME} HelmChart rollout did not complete successfully within 20 minutes."
-              exit 1
-            fi
-          permissions: 0777
-      commands:
-        - "KUBECONFIG=/etc/rancher/k3s/k3s.yaml nohup /bin/bash /tmp/cilium-manifest.sh > /tmp/cilium-apply.out 2>&1 &"
-    - name: "Add cluster-specific manifests: kube-vip"
-      if: "[ ! -e /var/lib/rancher/k3s/server/manifests/kube-vip-helmchart.applied ] && [ -e /etc/rancher/k3s/k3s.yaml ]"
-      downloads:
-        - url: https://raw.githubusercontent.com/6ixfalls/homelab-gitops/main/bootstrap/kube-vip.yaml
-          path: /var/lib/rancher/k3s/server/manifests/kube-vip-helmchart.yaml
-      files:
-        - path: /tmp/kube-vip-manifest.sh
-          content: |
-            #!/bin/bash
-            NAMESPACE="kube-system"
-            HELM_CHART_NAME="kube-vip"
-            KUBECONFIG="/etc/rancher/k3s/k3s.yaml"
-
-            if ! /tmp/get-manifest-lock.sh $HELM_CHART_NAME; then
-              echo "Lock was not obtained"
-              exit 0
-            fi
-
-            helm_release_exists() {
-              kubectl get helmchart ${HELM_CHART_NAME} -n ${NAMESPACE} &> /dev/null
-            }
-
-            while ! helm_release_exists; do
-              echo "Helm release not found. Retrying in 5 seconds..."
-              sleep 5
-            done
-
-            # Wait for HelmChart to rollout
-            if kubectl wait --for=condition=complete job/helm-install-${HELM_CHART_NAME} -n ${NAMESPACE} --timeout=20m; then
-              # Patch the HelmChart to unmanage it
-              kubectl patch helmchart ${HELM_CHART_NAME} -n ${NAMESPACE} \
-                  --type=json -p='[{"op": "add", "path": "/metadata/annotations/helmcharts.helm.cattle.io~1unmanaged", "value": "true"}]'
-
-              # Delete the HelmChart CR
-              kubectl delete helmchart ${HELM_CHART_NAME} -n ${NAMESPACE} &
-
-              # Force delete the HelmChart
-              kubectl patch helmchart ${HELM_CHART_NAME} -n ${NAMESPACE} \
-                  --type=json -p='[{"op": "replace", "path": "/metadata/finalizers", "value": []}]'
-
-              # Delete the manifests
-              rm -f /var/lib/rancher/k3s/server/manifests/kube-vip-helmchart.yaml
-              touch /var/lib/rancher/k3s/server/manifests/kube-vip-helmchart.applied
-            else
-              echo "${HELM_CHART_NAME} HelmChart rollout did not complete successfully within 20 minutes."
-              exit 1
-            fi
-          permissions: 0777
-      commands:
-        - "KUBECONFIG=/etc/rancher/k3s/k3s.yaml nohup /bin/bash /tmp/kube-vip-manifest.sh > /tmp/kube-vip-apply.out 2>&1 &"
